config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  resources :guitars
  resources :brands do 
    resources :models
  end
  resources :posts
  devise_for :users
  
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
end

app/models/application_record.rb
# SUPER Class
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
# Brand
class Brand < ApplicationRecord
    has_many :models

    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/guitar.rb
# Guitar
class Guitar < ApplicationRecord
  belongs_to :model
  belongs_to :brand
  belongs_to :user

  validates :purchase_year, presence: true
end

app/models/model.rb
# Model
class Model < ApplicationRecord
  enum style: { single_cut: 0, double_cut: 1, strato: 2, tele: 3, hollow: 4, misc: 5 }
  belongs_to :brand
  has_many :guitars

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :style, presence: true
end

app/models/post.rb
# POST Model
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'

  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :not_draft, -> { where.not(published_at: nil).order(published_at: :desc) }
  scope :published, -> { where('published_at <= ?', Time.current).order(published_at: :desc) }
  scope :scheduled, -> { where('published_at > ?', Time.current).order(published_at: :desc) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
# User model
class User < ApplicationRecord
  enum role: { regular: 0, admin: 1 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :posts, dependent: :destroy_async
  has_many :guitars, dependent: :destroy_async

  validates :email, presence: { uniqueness: true }
  validates :encrypted_password, presence: true
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to model_url(@model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to model_url(@model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy!

    respond_to do |format|
      format.html { redirect_to models_url, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:name, :description, :style, :brand_id)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.number_field :style %>
  </div>

  <div>
    <%= form.label :brand_id, style: "display: block" %>
    <%= form.text_field :brand_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div id="<%= dom_id model %>">
  <p>
    <strong>Name:</strong>
    <%= model.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= model.description %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= model.style %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= model.brand_id %>
  </p>

</div>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Show this model", @model %> |
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Models</h1>

<div id="models">
  <% @models.each do |model| %>
    <%= render model %>
    <p>
      <%= link_to "Show this model", model %>
    </p>
  <% end %>
</div>

<%= link_to "New model", new_model_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_model_path(@model) %> |
  <%= link_to "Back to models", models_path %>

  <%= button_to "Destroy this model", @model, method: :delete %>
</div>