config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  resources :guitars
  resources :brands do 
    resources :models
  end
  resources :posts
  devise_for :users
  
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
end

app/models/guitar.rb
# Guitar
class Guitar < ApplicationRecord
  belongs_to :model
  belongs_to :brand
  belongs_to :user

  validates :purchase_year, presence: true
end

app/controllers/guitars_controller.rb
# Guitars
class GuitarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_guitar, only: %i[ show edit update destroy ]

  # GET /guitars or /guitars.json
  def index
    if params[:model].present?
      @model = Model.find(params[:model])
      @guitars = Guitar.where(model: params[:model])
    else
      @model = nil
      @guitars = Guitar.all
    end
  end

  # GET /guitars/1 or /guitars/1.json
  def show
  end

  # GET /guitars/new
  def new
    @guitar = Guitar.new
  end

  # GET /guitars/1/edit
  def edit
  end

  # POST /guitars or /guitars.json
  def create
    @guitar = Guitar.new(guitar_params)

    respond_to do |format|
      if @guitar.save
        format.html { redirect_to guitar_url(@guitar), notice: "Guitar was successfully created." }
        format.json { render :show, status: :created, location: @guitar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guitars/1 or /guitars/1.json
  def update
    respond_to do |format|
      if @guitar.update(guitar_params)
        format.html { redirect_to guitar_url(@guitar), notice: "Guitar was successfully updated." }
        format.json { render :show, status: :ok, location: @guitar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guitars/1 or /guitars/1.json
  def destroy
    @guitar.destroy!

    respond_to do |format|
      format.html { redirect_to guitars_url, notice: "Guitar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guitar
      @guitar = Guitar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guitar_params
      params.require(:guitar).permit(:model_id, :brand_id, :name, :description, :series_number, :purchase_date, :purchase_year, :second_hand, :shop_name, :picture)
    end
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/views/guitars/_form.html.erb
<%= form_with(model: guitar) do |form| %>
  <% if guitar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guitar.errors.count, "error") %> prohibited this guitar from being saved:</h2>

      <ul>
        <% guitar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :model_id, style: "display: block" %>
    <%= form.text_field :model_id %>
  </div>

  <div>
    <%= form.label :brand_id, style: "display: block" %>
    <%= form.text_field :brand_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :series_number, style: "display: block" %>
    <%= form.text_field :series_number %>
  </div>

  <div>
    <%= form.label :purchase_date, style: "display: block" %>
    <%= form.date_field :purchase_date %>
  </div>

  <div>
    <%= form.label :purchase_year, style: "display: block" %>
    <%= form.number_field :purchase_year %>
  </div>

  <div>
    <%= form.label :second_hand, style: "display: block" %>
    <%= form.check_box :second_hand %>
  </div>

  <div>
    <%= form.label :shop_name, style: "display: block" %>
    <%= form.text_field :shop_name %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guitars/_guitar.html.erb
<div id="<%= dom_id guitar %>" class="w3-row">

  <div class="w3-col m6 l5 w3-card-4 w3-round w3-center">
    <% if guitar.picture.present? %>
      <%= image_tag guitar.picture, alt: "Guitar Picture", class: "guitar-picture w3-center" %>
    <% else %>
      <%= image_tag "shadow.png", alt: "Guitar Picture", class: "guitar-picture w3-center" %>
    <% end %>
  </div>

  <div class="w3-col m5 l6 w3-padding w3-margin">  
    <h1><%= guitar.name %></h1>

    <h3>Specifications</h3>
    <table class="w3-table w3-card-2 w3-round">
      <tr>
        <td><strong>Model</strong></td>
        <td>&nbsp;</td><td><%= "#{guitar.brand.name} #{guitar.model.name}" %></td>
      </tr>
      <tr>
        <td><strong>Series Number</strong></td>
        <td>&nbsp;</td><td><code><%= guitar.series_number %></code></td>
      </tr>
      <tr>
        <td><strong>Purchase Date</strong></td>
        <td>&nbsp;</td><td><%= guitar.purchase_date.present? ? guitar.purchase_date : guitar.purchase_year %></td>
      </tr>
    </table>
    
    <% if guitar.description.present? %>
      <hr />
      <h3>Description</h3>
      <p>
        <%= guitar.description %>
      </p>
    <% end %>
    
    <% if guitar.second_hand || guitar.shop_name.present? %>
      <hr />
      <% if guitar.second_hand %>
        <p>Second hand</p>
      <% end %>
      <% if guitar.shop_name.present? %>
        <p><strong>Shop name:</strong><%= guitar.shop_name %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/guitars/edit.html.erb
<h1>Editing guitar</h1>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Show this guitar", @guitar %> |
  <%= link_to "Back to guitars", guitars_path %>
</div>

app/views/guitars/index.html.erb
<p style="color: green"><%= notice %></p>


<% if @model.present? %>
  <h1><%= @model.brand.name %></h1>
  <h2><%= @model.name %></h2>
<% else %>
  <h1>Guitars</h1>
<% end %>

<%= link_to "New guitar", new_guitar_path, class: "w3-right" %>

<table id="guitars" class="w3-table-all w3-hoverable">
  <thead>
    <tr>
      <th>Model</th>
      <th>Name</th>
      <th class="w3-hide-small">Purchase Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @guitars.each do |guitar| %>
      <tr>
        <td><%= "#{guitar.brand.name} #{guitar.model.name}" %></td>
        <td><%= guitar.name %></td>
        <td class="w3-hide-small"><%= guitar.purchase_year %></td>
        <td title="View this guitar"><%= link_to "<i class='material-symbols-rounded'>visibility</i>".html_safe, guitar %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New guitar", new_guitar_path %>

app/views/guitars/new.html.erb
<h1>New guitar</h1>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Back to guitars", guitars_path %>
</div>

app/views/guitars/show.html.erb
<div class="w3-margin">
  <%= render @guitar %>
  <div>
    <%= link_to "Edit this guitar", edit_guitar_path(@guitar) %> |
    <%= link_to "Back to guitars", guitars_path %>
    <%= button_to "Destroy this guitar", @guitar, method: :delete %>
  </div>
</div>