config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  resources :guitars
  resources :brands do 
    resources :models
  end
  resources :posts
  devise_for :users
  
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
end

app/models/brand.rb
# Brand
class Brand < ApplicationRecord
    has_many :models

    validates :name, presence: true
    validates :name, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.order(:name)
  end

  # GET /brands/1 or /brands/1.json
  def show
    @models = @brand.models.order(:name)
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy!

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description, :website)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <h2><%= brand.name %></h2>

  <p>
    <strong>Description:</strong>
    <%= brand.description %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= brand.website %>
  </p>

</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Brands</h1>

<div class="w3-right"><%= link_to "New brand", new_brand_path %></div>

<table id="brands" class="w3-table-all w3-hoverable">
  <thead class="w3-hide-small">
    <tr>
      <th>Brand Name</th>
      <th class="w3-hide-small">Website</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td class="w3-hide-small"><%= brand.website %></td>
        <td class="w3-right">
          <%= link_to "<i class='material-symbols-rounded'>visibility</i>".html_safe, brand, title: "View models" %>
          <%= link_to "<i class='material-symbols-rounded'>edit</i>".html_safe, "#", title: "Edit" %>
          <%= link_to "<i class='material-symbols-rounded'>delete</i>".html_safe, "#", title: "Delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New brand", new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brand %>

<h3>Models</h3>

<table id="models" class="w3-table-all w3-hoverable">
  <thead>
    <tr>
      <th>Model</th>
      <th>Style</th>
      <th class="w3-hide-small">Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.name %></td>
        <td><%= model.style %></td>
        <td class="w3-hide-small"><%= model.description %></td>
        <td class="w3-right"><%= link_to "<i class='material-symbols-rounded'>visibility</i>".html_safe, guitars_path(model: model), class: "w3-button", title: "View the guitars" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this brand", edit_brand_path(@brand) %> |
  <%= link_to "Back to brands", brands_path %>

  <%= button_to "Destroy this brand", @brand, method: :delete %>
</div>